### ISSUE TITLE
Fatal Error, TyposcriptUtility not found - MeLibrary missing

### ISSUE THREAD

**Issue by alexdpunkt** [move-elevator/me_cleverreach#1]
I just installed the extension (TYPO3 6.2.3), inserted the plugin on a page, and get the following error: 

`Fatal error: Class 'MoveElevator\MeLibrary\Utility\TyposcriptUtility' not found in /html/typo3/typo3conf/ext/me_cleverreach/Classes/Utility/SettingsUtility.php on line 63`

MeLibrary is missing.
There's also no dependency to EXT:me_library in ext_emconf.php 

Current workaround: don't execute `getExtensionSettingsByTypoScript`

```
class SettingsUtility {
    /**
     * Get settings from TypoScript and form extension configuration.
     * TypoScript overwrite settings from extension configuration.
     *
     * @return array
     */
    static public function getSettings() {
        $settings = array();

        $settingsConfVars = self::getExtensionSettingsByConfVars();
        /*
        $settingsTypoScript = self::getExtensionSettingsByTypoScript();
        $settings['config'] = array_merge(
            $settingsConfVars['config'],
            $settingsTypoScript['config']
        );

        return $settings;
        */

        return $settingsConfVars;
    }
```

Too bad that I need to override the settings via typoscript for the english form...

**Comment by freshp** [comment]
Hello adick!

thank you for your feedback. We had solved the issue and add the _TyposcriptUtility_ to this extension. 

You can also use the new version 1.0.4 from http://typo3.org/extensions/repository/view/me_cleverreach

best regards
Steve
move : elevator
