### ISSUE TITLE
Form action is missing L-parameter

### ISSUE THREAD

**Issue by ghost** [move-elevator/me_cleverreach#2]
On translated pages the form action attribute of the subscription form is missing the L get parameter. So on form submit you get redirected to the original language.

**Comment by janmaennig** [comment]
Hello derghostface,

the form action is generated by TYPO3. If you need the language param you can try to use the additionalParams to extend the action uri.

best regards
Jan

**Comment by ghost** [comment]
Thank you for the hint!
